databaseChangeLog:
  - changeSet:
      id: create-application-user-table
      author: James Carman
      changes:
        - createTable:
            tableName: application_user
            columns:
              - column:
                  name: id
                  type: VARCHAR(255)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: version
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: created_date
                  type: TIMESTAMP WITH TIME ZONE
                  defaultValueComputed: 'CURRENT_TIMESTAMP'
                  constraints:
                    nullable: false
              - column:
                  name: modified_date
                  type: TIMESTAMP WITH TIME ZONE
                  defaultValueComputed: 'CURRENT_TIMESTAMP'
                  constraints:
                    nullable: false
              - column:
                  name: created_by
                  type: VARCHAR(255)
                  defaultValue: 'SYSTEM'
                  constraints:
                    nullable: false
              - column:
                  name: modified_by
                  type: VARCHAR(255)
                  defaultValue: 'SYSTEM'
                  constraints:
                    nullable: false
              - column:
                  name: user_name
                  type: VARCHAR(255)
                  constraints:
                      nullable: false
              - column:
                  name: first_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: last_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: email
                  type: VARCHAR(255)
                  constraints:
                    nullable: false