name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -Drevision=$GITHUB_RUN_NUMBER verify
    - name: Build Image
      run: mvn -Pnative -DskipTests -Drevision=$GITHUB_RUN_NUMBER spring-boot:build-image
    - name: Extract Image Name
      run: |
        echo "IMAGE_NAME=$(mvn help:evaluate -Drevision=$GITHUB_RUN_NUMBER -Dexpression=image.name -q -DforceStdout)" >> $GITHUB_ENV
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Image
      run: |
          docker push $IMAGE_NAME